package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager(){
        manager = Managers.getDefault();
    }

    @Test
    public void testAddTask() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId(){
        Task task = new Task(42, "Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @Test
    public void testAddTaskWithAndWithoutId(){
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
        assertEquals(2, task1.getId(), "task id has to be sequential");
    }

    @Test
    public void checkTaskNotChangedAfterAddTask() {
        int id = 1;
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task(id, name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(task1after.getId(), id);
        assertEquals(task1after.getDescription(), description);
        assertEquals(task1after.getStatus(), status);
        assertEquals(task1after.getName(), name);
    }

    @Test
    public void checkTaskRemoval() {
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        manager.getTask(task0.getId());
        manager.getTask(task1.getId());

        manager.deleteTask(task0.getId());

        List<Integer> historyTaskIds = manager.getHistory().stream().map(Task::getId).toList();
        List<Task> remainingTasks = manager.getTasks();
        assertEquals(1, remainingTasks.size(), "remaining task should also be removed");
        assertEquals(1, historyTaskIds.size(), "task should also be removed from history");
        assertEquals(List.of(task1.getId()), historyTaskIds);
    }

    @Test
    public void checkEpicSubtaskRemoval() {
        Epic epic = new Epic("Epic1", "Epic desc");
        int epicId = manager.addNewEpic(epic);
        List<Subtask> epicSubtasks = getEpicSubtasks(epicId);
        List<Integer> subTaskIds = epicSubtasks.stream().map(epicSubtask -> manager.addNewSubtask(epicSubtask)).toList();
        manager.getEpic(epicId);
        manager.getSubtask(subTaskIds.get(0));
        manager.getSubtask(subTaskIds.get(1));

        manager.deleteSubtask(subTaskIds.get(0));

        List<Task> history = manager.getHistory();
        assertFalse(history.contains(epicSubtasks.getFirst()));
        assertTrue(history.contains(epic));
    }

    @Test
    public void checkEpicRemoval() {
        Epic epic = new Epic("Epic1", "Epic desc");
        int epicId = manager.addNewEpic(epic);
        List<Subtask> epicSubtasks = getEpicSubtasks(epicId);
        List<Integer> subTaskIds = epicSubtasks.stream().map(epicSubtask -> manager.addNewSubtask(epicSubtask)).toList();
        manager.getEpic(epicId);
        manager.getSubtask(subTaskIds.get(0));
        manager.getSubtask(subTaskIds.get(1));

        manager.deleteEpic(epicId);

        assertTrue(manager.getHistory().isEmpty());
        assertTrue(manager.getSubtasks().isEmpty());
        assertTrue(manager.getEpics().isEmpty());
    }

    private List<Subtask> getEpicSubtasks(int epicId) {
        return List.of(
                new Subtask("SubT1", "Desc1", TaskStatus.NEW, epicId),
                new Subtask("SubT2", "Desc2", TaskStatus.NEW, epicId),
                new Subtask("SubT3", "Desc3", TaskStatus.NEW, epicId),
                new Subtask("SubT4", "Desc4", TaskStatus.NEW, epicId)
        );
    }
}
