package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import ru.yandex.javacourse.schedule.tasks.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

public class TaskManagersTest {
    private static final Path TASKS_FILE = Paths.get("tasks.csv");

    @AfterAll
    public static void cleanUpAll() throws IOException {
        Files.deleteIfExists(TASKS_FILE);
    }

    static Stream<TaskManager> managerProvider() {
        return Stream.of(
                Managers.getDefault(),
                Managers.getFileBackedTaskManager()
        );
    }

    @ParameterizedTest
    @MethodSource("managerProvider")
    public void testAddTask(TaskManager manager) {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW, TaskType.TASK);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().getFirst();
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @ParameterizedTest
    @MethodSource("managerProvider")
    public void testAddTaskWithId(TaskManager manager){
        Task task = new Task(42, "Test 1", "Testing task 1", TaskStatus.NEW, TaskType.TASK);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().getFirst();
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @ParameterizedTest
    @MethodSource("managerProvider")
    public void testAddTaskWithAndWithoutId(TaskManager manager){
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW, TaskType.TASK);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW, TaskType.TASK);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
        assertEquals(2, task1.getId(), "task id has to be sequential");
    }

    @ParameterizedTest
    @MethodSource("managerProvider")
    public void checkTaskNotChangedAfterAddTask(TaskManager manager) {
        int id = 1;
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = TaskStatus.NEW;
        TaskType taskType = TaskType.TASK;
        Task task1before = new Task(id, name, description, status, taskType);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(id, task1after.getId());
        assertEquals(description, task1after.getDescription());
        assertEquals(status, task1after.getStatus());
        assertEquals(name, task1after.getName());
    }

    @ParameterizedTest
    @MethodSource("managerProvider")
    public void checkTaskRemoval(TaskManager manager) {
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW, TaskType.TASK);
        Task task1 = new Task(1, "Test 2", "Testing task 2", TaskStatus.NEW, TaskType.TASK);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        manager.getTask(task0.getId());
        manager.getTask(task1.getId());

        manager.deleteTask(task0.getId());

        List<Integer> historyTaskIds = manager.getHistory().stream().map(Task::getId).toList();
        List<Task> remainingTasks = manager.getTasks();
        assertEquals(1, remainingTasks.size(), "remaining task should also be removed");
        assertEquals(1, historyTaskIds.size(), "task should also be removed from history");
        assertEquals(List.of(task1.getId()), historyTaskIds);
    }

    @ParameterizedTest
    @MethodSource("managerProvider")
    public void checkEpicSubtaskRemoval(TaskManager manager) {
        Epic epic = new Epic("Epic1", "Epic desc");
        int epicId = manager.addNewEpic(epic);
        List<Subtask> epicSubtasks = getEpicSubtasks(epicId);
        List<Integer> subTaskIds = epicSubtasks.stream().map(manager::addNewSubtask).toList();
        manager.getEpic(epicId);
        manager.getSubtask(subTaskIds.get(0));
        manager.getSubtask(subTaskIds.get(1));

        manager.deleteSubtask(subTaskIds.get(0));

        List<Task> history = manager.getHistory();
        assertFalse(history.contains(epicSubtasks.getFirst()));
        assertTrue(history.contains(epic));
    }

    @ParameterizedTest
    @MethodSource("managerProvider")
    public void checkEpicRemoval(TaskManager manager) {
        Epic epic = new Epic("Epic1", "Epic desc");
        int epicId = manager.addNewEpic(epic);
        List<Subtask> epicSubtasks = getEpicSubtasks(epicId);
        List<Integer> subTaskIds = epicSubtasks.stream().map(manager::addNewSubtask).toList();
        manager.getEpic(epicId);
        manager.getSubtask(subTaskIds.get(0));
        manager.getSubtask(subTaskIds.get(1));

        manager.deleteEpic(epicId);

        assertTrue(manager.getHistory().isEmpty());
        assertTrue(manager.getSubtasks().isEmpty());
        assertTrue(manager.getEpics().isEmpty());
    }

    private List<Subtask> getEpicSubtasks(int epicId) {
        return List.of(
                new Subtask("SubT1", "Desc1", TaskStatus.NEW, epicId),
                new Subtask("SubT2", "Desc2", TaskStatus.NEW, epicId),
                new Subtask("SubT3", "Desc3", TaskStatus.NEW, epicId),
                new Subtask("SubT4", "Desc4", TaskStatus.NEW, epicId)
        );
    }
}
